### ISSUE TITLE
_

### ISSUE THREAD

**Issue by ghost** [carstenschaefer/redactor-fontSize#1]
_

**Comment by stehlo** [comment]
I am re-writing the plugin. It is just taking some time, as I am not familiar with either the Redactor nor your plugin.

**Comment by stehlo** [comment]
OK, the plugin was completely re-written. However, it is very bespoke in relation to the client's website, so it can't be made public.

**Comment by carstenschaefer** [comment]
Stehlo, wow, many thanks! I will check.

**Comment by carstenschaefer** [comment]
btw, there is no PR

**Comment by stehlo** [comment]
Hello Carsten,
I am afraid, there won't be anything to check. As stated above, the changed code is so specific that it can't be made available for general usage in the current form. It would need to be changed again.
Can you explain the "PR" abbreviation mentioned above, please?
Kind regards,
Tomas
